[build]
opt_level = 2
out_dir = "dist"

[ios]
certificate = "/Users/amlug/.perry/distribution.p12"
distribute = "testflight"
encryption_exempt = true
provisioning_profile = "/Users/amlug/.perry/com_bloomengine_garden.mobileprovision"

[project]
entry = "src/main.ts"
name = "bloom-garden"
